#!/bin/sh

BACKUP_FOLDER=/opt/mysql/backup
NOW=$(date '+%d')

GZIP=tar

### MySQL Server Login info ###
MDB=redmine
MHOST=db
MPASS=redmine
MUSER=root

[ ! -d "$BACKUP_FOLDER" ] && mkdir --parents $BACKUP_FOLDER

FILE=${BACKUP_FOLDER}/backup-${NOW}.sql.gz
mysqldump -h $MHOST -u $MUSER -p${MPASS} --databases $MDB | $GZIP -9 > $FILE
